    <title>Kalakal | A B2B Wholesale E-Commerce Platform</title>
    <!-- Plugin CSS -->
    <link href="<?php echo base_url('assets/css/style.css'); ?>" type="text/css" rel="stylesheet" media="screen,projection">


  </head>
  <body>
    <div class="navbar-fixed">
      <nav class="white navbar-fixed main-navigation" role="navigation">
        <div class="nav-wrapper container">
          <a id="logo-container" href="<?php echo base_url()?>" class="brand-logo ">Kalakal.ph</a>
          <ul class="right hide-on-med-and-down">
            <li><a href="<?php echo base_url()?>login">Login</a></li>
            <li><a href="<?php echo base_url()?>register">Register</a></li>
            <li><a class="nav-link js-scroll-trigger" href="#features">Features</a></li>
            <li><a class="nav-link js-scroll-trigger" href="#newsletter">Newsletter</a></li>
            <li><a class="orange waves-effect waves-light btn" href="<?php echo base_url()?>store">Visit Store</a></li>
          </ul>

          <!-- Navbar converts to side menu when mobile mode -->
          <ul id="nav-mobile" class="side-nav">
            <li><a href="<?php echo base_url()?>login">Login</a></li>
            <li><a href="<?php echo base_url()?>register">Register</a></li>
            <li><a href="#features">Features</a></li>
            <li><a href="#newsletter">Newsletter</a></li>
            <li><a class="orange waves-effect waves-light btn" href="#">Visit Store</a></li>
          </ul>
          <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
      </nav>
    </div>


  <div id="index-banner" class="parallax-container" style="padding: 100px">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center orange-text text-lighten-2">Jumpstart your Business</h1>
        <div class="row center">
          <h5 class="header col s12 light"> Kalakal is a B2B wholesale e-commerce
            platform for entrepreneurs looking for goods at the best price</h5>
        </div>
        <div class="row center">
          <div class="input-field col s8">
            <input type="text" class="validate">
            <label for="first_name">Email Address</label>
          </div>
          <div class="col s4">
            <a href="#" id="submit-button" class="btn-large waves-effect waves-light orange lighten-1">Get Started</a>
          </div>
        </div>
        <br><br>
      </div>
    </div>
    <div class="parallax"><img src="<?php echo base_url('assets/img/header.jpg')?>" alt="Unsplashed background img 1"></div>
  </div>

  <!-- Feature Section -->
  <div id="features" class="blue-grey parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h3 class="header s12 light">Everything you need to grow your business</h3>
          <p>Kalakal helps small and medium enterprises to manage their business
            <br> by making most of the process online and digital. A simple solution
            that will help your brand sell more</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Icon Section -->
  <div class="container">
    <div class="section">
      <div class="row">

        <div class="col s4" style="padding: auto;">
          <div class="icon-block">
            <div>
              <img class="responsive-img" style= "padding: 50px 60px 0px 60px;"
                  src="<?php echo base_url('assets/img/store-icon.png');?>"
                  alt="error">
            </div>
            <h5 class="center">Setup your own store</h5>
            <p class="light">We help business owners to scale their business by being
                            the podium for their products and services online</p>
          </div>
        </div>

        <div class="col s4" style="padding: auto;">
           <div class="icon-block">
             <div>
               <img class="responsive-img" style="padding: 50px 60px 0px 60px;"
                    src="<?php echo base_url('assets/img/delivery-icon.png');?>"
                    alt="error">
             </div>
             <h5 class="center">Track package deliveries</h5>
             <p class="light">Keep updated with your packages thru the tracking f
                              eature of the system</p>
           </div>
         </div>

         <div class="col s4" style="padding: auto;">
           <div class="icon-block">
             <div>
               <img class="responsive-img" style="padding: 50px 60px 0px 60px;"
                    src="<?php echo base_url('assets/img/reports-icon.png');?>"
                    alt="error">
              </div>
              <h5 class="center">Generate sales reports</h5>
              <p class="light"> View your sales automatically by the reports
                                 generated by the system </p>
           </div>
         </div>
      </div>
    </div>
  </div>

<!-- Newsletter Section -->
  <div id=newsletter class="parallax-container valign-wrapper">
      <div class="section no-pad-bot">
        <div class="container">
          <div class="row center">

            <h5 class="header col s12 light">Interested? We'd love to connect!</h5>
            <form method="post" action="<?php echo base_url();?>Newsletter_controller/submit">
              <div class="row">
              <div class="input-field col s12">
                <input type="text" class="validate" name="name" id="name" required>
                <label for="name">Name</label>
              </div>
              <div class="input-field col s12">
                <input type="text" class="validate" name="email" id="email" required>
                <label for="email_address">Email Address</label>
              </div>
              <input type="submit" class="btn"  name="submit" value="SUBMIT">
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="parallax"><img src="<?php echo base_url('assets/img/header.jpg');?>" alt="error"></div>
    </div>
